# Generated by Django 3.2.2 on 2021-05-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetsAdoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='vaccination',
            new_name='vaccinations',
        ),
    ]
